{{- range $name, $app := .Values.apps }}
{{- if ne $app.enabled false }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $name }}-{{ $.Values.clusterName }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "platform.labels" $ | nindent 4 }}
  {{- with $app.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  project: default
  source:
    repoURL: {{ $app.repoURL }}
    {{- if $app.path }}
    path: {{ $app.path }}
    {{- else }}
    chart: {{ $app.chart }}
    {{- end }}
    targetRevision: {{ $app.version }}
    {{- if $app.values }}
    helm:
      values: |
        {{- toYaml $app.values | nindent 8 }}
    {{- end }}
  destination:
    name: {{ $.Values.destination.name }}
    namespace: {{ $app.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
---
{{- end }}
{{- end }}
