# Default values for platform.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

nameOverride: ""
fullnameOverride: ""

destination:
  name: ""

apps:
  envoy-gateway:
    repoURL: "registry-1.docker.io/envoyproxy"
    chart: "gateway-helm"
    version: "v1.6.1"
    namespace: "envoy-gateway-system"

  gateway:
    repoURL: "https://github.com/rafal-jan/application-set-demo"
    path: "platform-apps/gateway"
    version: "HEAD"
    namespace: "envoy-gateway-system"
    annotations:
      argocd.argoproj.io/sync-wave: "1"
