apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: workload-apps
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - matrix:
      generators:
      - git:
          repoURL: ${REPO_URL}
          revision: HEAD
          requeueAfterSeconds: 30
          files:
          - path: "apps/*/values/*/values.yaml"
      - clusters:
          selector:
            matchLabels:
              env: '{{index .path.segments 3}}'
  template:
    metadata:
      name: '{{index .path.segments 1}}-{{.name}}'
    spec:
      project: default
      source:
        repoURL: ${REPO_URL}
        path: 'apps/{{index .path.segments 1}}/chart'
        helm:
          valueFiles:
          - '../../../global/{{index .path.segments 3}}.yaml'
          - '../values/{{index .path.segments 3}}/values.yaml'
      destination:
        server: '{{.server}}'
        namespace: '{{index .path.segments 1}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
          allowEmpty: true
        syncOptions:
          - CreateNamespace=true
  templatePatch: |
    spec:
      syncPolicy:
        automated:
          enabled: {{ dig "autoSync" true . }}
